mv_gefs_gdas_rtps_href_spring_2022:
    HREF:
        short_name: 'href'
        num_ens_mems: 10
    RRFS_GDAS_GF.SPP.SPPT:
        short_name: 'gdas'
        num_ens_mems: 10
    RRFS_GEFS_GF.SPP.SPPT:
        short_name: 'gefs'
        num_ens_mems: 10
    RTPS:
        short_name: 'rtps'
        num_ens_mems: 10
