mv_host: 'mohawk'

mv_database_name: 'mv_gefs_gdas_rtps_href_spring_2022'

model_names: ['href', 'gdas', 'gefs']

fcst_init_info:
    fcst_init_time_first: '2022050100'
    num_fcst_inits: 6
    fcst_init_intvl_hrs: 24

fcst_len_hrs: 36

metrics_fields_levels_threshes:
    #
    auc:
        apcp:
            03h: ['gt0.0mm', 'ge2.54mm']
        dpt:
            2m: ['ge288K', 'ge293K']
        refc:
            L0: ['ge20dBZ', 'ge30dBZ', 'ge40dBZ', 'ge50dBZ']
        tmp:
            2m: ['ge293K', 'ge298K']
            850mb: ['ge288K']
        wind:
            10m: ['ge5mps', 'ge10mps']
            700mb: ['ge10mps']
    #
    bias:
        dpt:
            2m: []
        refc:
            L0: []
        tmp:
            2m: []
            500mb: []
            700mb: []
            850mb: []
        wind:
            10m: []
            700mb: []
            850mb: []
    #
    brier:
        apcp:
            03h: ['gt0.0mm', 'ge2.54mm']
        dpt:
            2m: ['ge288K', 'ge293K']
        refc:
            L0: ['ge20dBZ', 'ge30dBZ', 'ge40dBZ', 'ge50dBZ']
        tmp:
            2m: ['ge293K', 'ge298K']
            850mb: ['ge288K']
        wind:
            10m: ['ge5mps', 'ge10mps']
            700mb: ['ge10mps']
    #
    fbias:
        apcp:
            03h: ['gt0.0mm', 'ge2.54mm']
        refc:
            L0: ['ge20dBZ', 'ge30dBZ', 'ge40dBZ', 'ge50dBZ']
    #
    rely:
        apcp:
            03h: ['gt0.0mm', 'ge0.508mm', 'ge2.54mm', 'ge6.35mm']
            06h: ['ge6.35mm', 'ge12.7mm']
            24h: ['ge25.4mm']
        dpt:
            2m: ['ge288K', 'ge293K']
        refc:
            L0: ['ge20dBZ', 'ge30dBZ', 'ge40dBZ']
        tmp:
            2m: ['ge293K', 'ge298K', 'ge303K']
            850mb: ['ge288K']
        wind:
            10m: ['ge5mps', 'ge10mps']
            700mb: ['ge10mps']
    #
    rhist:
        apcp:
            03h: []
            06h: []
            24h: []
        cape:
            L0: []
        dpt:
            2m: []
        hgt:
            500mb: []
        refc:
            L0: []
        tmp:
            2m: []
            500mb: []
            850mb: []
        wind:
            10m: []
            500mb: []
            850mb: []
    #
    ss:
        apcp:
            03h: []
        dpt:
            2m: []
        hgt:
            500mb: []
        refc:
            L0: []
        tmp:
            2m: []
            500mb: []
            700mb: []
            850mb: []
        wind:
            500mb: []
            700mb: []
            850mb: []

