'APCP': {
    'APCP': {'A1': ['gt0.0', 'ge0.254', 'ge0.508', 'ge1.27', 'ge2.54'],
             'A3': ['gt0.0', 'ge0.254', 'ge0.508', 'ge1.27', 'ge2.54', 'ge3.810', 'ge6.350'],
             'A6': ['gt0.0', 'ge0.254', 'ge0.508', 'ge1.27', 'ge2.54', 'ge3.810', 'ge6.350', 'ge8.890', 'ge12.700'],
             'A24': ['gt0.0', 'ge0.254', 'ge0.508', 'ge1.27', 'ge2.54', 'ge3.810', 'ge6.350', 'ge8.890', 'ge12.700', 'ge25.400']}, },
'REFC': {
    'REFC': {'L0': ['ge20', 'ge30', 'ge40', 'ge50']}, },
'RETOP': {
    'RETOP': {'L0': ['ge20', 'ge30', 'ge40', 'ge50']}, },
'ADPSFC': {
    'TMP': {'Z2': []},
    'DPT': {'Z2': []},
    'RH': {'Z2': []},
    'UGRD': {'Z10': ['ge2.572']},
    'VGRD': {'Z10': ['ge2.572']},
    'WIND': {'Z10': ['ge2.572', 'ge2.572&&lt5.144', 'ge5.144', 'ge10.288', 'ge15.433']},
    'PRMSL': {'Z0': []},
    'TCDC': {'L0': []},
    'VIS': {'L0': ['lt805', 'lt1609', 'lt4828', 'lt8045', 'ge8045', 'lt16090']},
    'GUST': {'Z0': []},
    'HGT': {'L0': ['lt152', 'lt305', 'lt914', 'lt1520', 'lt3040', 'ge914']},
    'SPFH': {'Z2': []},
    'CRAIN': {'L0': ['ge1.0']},
    'CSNOW': {'L0': ['ge1.0']},
    'CFRZR': {'L0': ['ge1.0']},
    'CICEP': {'L0': ['ge1.0']}, },
'ADPUPA': {
    'TMP': {'P1000': [],
            'P925': [],
            'P850': [],
            'P700': [],
            'P500': [],
            'P400': [],
            'P300': [],
            'P250': [],
            'P200': [],
            'P150': [],
            'P100': [],
            'P50': [],
            'P20': [],
            'P10': []},
    'RH': {'P1000': [],
           'P925': [],
           'P850': [],
           'P700': [],
           'P500': [],
           'P400': [],
           'P300': [],
           'P250': []},
    'DPT': {'P1000': [],
            'P925': [],
            'P850': [],
            'P700': [],
            'P500': [],
            'P400': [],
            'P300': []},
    'UGRD': {'P1000': ['ge2.572'],
             'P925': ['ge2.572'],
             'P850': ['ge2.572'],
             'P700': ['ge2.572'],
             'P500': ['ge2.572'],
             'P400': ['ge2.572'],
             'P300': ['ge2.572'],
             'P250': ['ge2.572'],
             'P200': ['ge2.572'],
             'P150': ['ge2.572'],
             'P100': ['ge2.572'],
             'P50': ['ge2.572'],
             'P20': ['ge2.572'],
             'P10': ['ge2.572']},
    'VGRD': {'P1000': ['ge2.572'],
             'P925': ['ge2.572'],
             'P850': ['ge2.572'],
             'P700': ['ge2.572'],
             'P500': ['ge2.572'],
             'P400': ['ge2.572'],
             'P300': ['ge2.572'],
             'P250': ['ge2.572'],
             'P200': ['ge2.572'],
             'P150': ['ge2.572'],
             'P100': ['ge2.572'],
             'P50': ['ge2.572'],
             'P20': ['ge2.572'],
             'P10': ['ge2.572']},
    'WIND': {'P1000': ['ge2.572', 'ge2.572&&lt5.144', 'ge5.144', 'ge10.288', 'ge15.433', 'ge20.577', 'ge25.722'],
             'P925': ['ge2.572', 'ge2.572&&lt5.144', 'ge5.144', 'ge10.288', 'ge15.433', 'ge20.577', 'ge25.722'],
             'P850': ['ge2.572', 'ge2.572&&lt5.144', 'ge5.144', 'ge10.288', 'ge15.433', 'ge20.577', 'ge25.722'],
             'P700': ['ge2.572', 'ge2.572&&lt5.144', 'ge5.144', 'ge10.288', 'ge15.433', 'ge20.577', 'ge25.722'],
             'P500': ['ge2.572', 'ge2.572&&lt5.144', 'ge5.144', 'ge10.288', 'ge15.433', 'ge20.577', 'ge25.722'],
             'P400': ['ge2.572', 'ge2.572&&lt5.144', 'ge5.144', 'ge10.288', 'ge15.433', 'ge20.577', 'ge25.722'],
             'P300': ['ge2.572', 'ge2.572&&lt5.144', 'ge5.144', 'ge10.288', 'ge15.433', 'ge20.577', 'ge25.722'],
             'P250': ['ge2.572', 'ge2.572&&lt5.144', 'ge5.144', 'ge10.288', 'ge15.433', 'ge20.577', 'ge25.722'],
             'P200': ['ge2.572', 'ge2.572&&lt5.144', 'ge5.144', 'ge10.288', 'ge15.433', 'ge20.577', 'ge25.722'],
             'P150': ['ge2.572', 'ge2.572&&lt5.144', 'ge5.144', 'ge10.288', 'ge15.433', 'ge20.577', 'ge25.722'],
             'P100': ['ge2.572', 'ge2.572&&lt5.144', 'ge5.144', 'ge10.288', 'ge15.433', 'ge20.577', 'ge25.722'],
             'P50': ['ge2.572', 'ge2.572&&lt5.144', 'ge5.144', 'ge10.288', 'ge15.433', 'ge20.577', 'ge25.722'],
             'P20': ['ge2.572', 'ge2.572&&lt5.144', 'ge5.144', 'ge10.288', 'ge15.433', 'ge20.577', 'ge25.722'],
             'P10': ['ge2.572', 'ge2.572&&lt5.144', 'ge5.144', 'ge10.288', 'ge15.433', 'ge20.577', 'ge25.722']},
    'HGT': {'P1000': [],
            'P950': [],
            'P925': [],
            'P850': [],
            'P700': [],
            'P500': [],
            'P400': [],
            'P300': [],
            'P250': [],
            'P200': [],
            'P150': [],
            'P100': [],
            'P50': [],
            'P20': [],
            'P10': []},
    'SPFH': {'P1000': [],
             'P850': [],
             'P700': [],
             'P500': [],
             'P400': [],
             'P300': []},
    'CAPE': {'L0': ['gt500', 'gt1000', 'gt1500', 'gt2000', 'gt3000', 'gt4000']},
    'HPBL': {'Z0': []}, },
