#
#-----------------------------------------------------------------------
#
# This file defines a function that sets various parameters needed when
# performing verification.  The way these parameters are set depends on
# the field group being verified and, if the field group consists of a 
# set of cumulative fields (e.g. accumulated precipitation or accumulated
# snowfall), the accumulation interval (both of which are inputs to this
# function).
#
# As of 20220928, the verification tasks in the SRW App workflow use the
# MET/METplus software (MET = Model Evaluation Tools) developed at the
# DTC (Developmental Testbed Center).
#
#-----------------------------------------------------------------------
#
function set_vx_params() {
#
#-----------------------------------------------------------------------
#
# Save current shell options (in a global array).  Then set new options
# for this script/function.
#
#-----------------------------------------------------------------------
#
  { save_shell_opts; set -u +x; } > /dev/null 2>&1
#
#-----------------------------------------------------------------------
#
# Get the full path to the file in which this script/function is located
# (scrfunc_fp), the name of that file (scrfunc_fn), and the directory in
# which the file is located (scrfunc_dir).
#
#-----------------------------------------------------------------------
#
  local scrfunc_fp=$( $READLINK -f "${BASH_SOURCE[0]}" )
  local scrfunc_fn=$( basename "${scrfunc_fp}" )
  local scrfunc_dir=$( dirname "${scrfunc_fp}" )
#
#-----------------------------------------------------------------------
#
# Get the name of this function.
#
#-----------------------------------------------------------------------
#
  local func_name="${FUNCNAME[0]}"
#
#-----------------------------------------------------------------------
#
# Specify the set of valid argument names for this script/function.  Then
# process the arguments provided to this script/function (which should
# consist of a set of name-value pairs of the form arg1="value1", etc).
#
#-----------------------------------------------------------------------
#
  local valid_args=( \
        "field_group" \
        "accum_hh" \
        "outvarname_obtype" \
        "outvarname_grid_or_point" \
        "outvarname_fieldgroup_in_MET_filedir_names" \
        )
  process_args valid_args "$@"
#
#-----------------------------------------------------------------------
#
# For debugging purposes, print out values of arguments passed to this
# script.  Note that these will be printed out only if VERBOSE is set to
# TRUE.
#
#-----------------------------------------------------------------------
#
  print_input_args valid_args
#
#-----------------------------------------------------------------------
#
# Declare local variables.
#
#-----------------------------------------------------------------------
#
  local _obtype_ \
        _grid_or_point_ \
        fieldgroup_in_MET_filedir_names
#
#-----------------------------------------------------------------------
#
# Make sure that accum_hh is a 2-digit integer.
#
#-----------------------------------------------------------------------
#
  if [ "${field_group}" = "APCP" ] || [ "${field_group}" = "ASNOW" ]; then
    if [[ ! "${accum_hh}" =~ ^[0-9]{2}$ ]]; then
      print_err_msg_exit "\
For the given field group (field_group), the accumulation (accum_hh) must
be a 2-digit integer:
  field_group = \"${field_group}\"
  accum_hh = \"${accum_hh}\""
    fi
  fi
#
#-----------------------------------------------------------------------
#
# Set the parameters.  Definitions:
#
# _obtype_:
# The observation type corresponding to the specified field group.
#
# _grid_or_point_:
# String that is set to either "grid" or "point" depending on whether
# obs type containing the field group is gridded or point-based.
#
# fieldgroup_in_MET_filedir_names:
# String that will be used in naming directories and files (e.g. NetCDF
# files, stat files, log files, staging directories) generated by MET
# or METplus.
#
#-----------------------------------------------------------------------
#
  _obtype_=""
  _grid_or_point_=""
  fieldgroup_in_MET_filedir_names=""

  case "${field_group}" in

    "APCP")
      _obtype_="CCPA"
      _grid_or_point_="grid"
      fieldgroup_in_MET_filedir_names="${field_group}${accum_hh}h"
      ;;

    "ASNOW")
      _obtype_="NOHRSC"
      _grid_or_point_="grid"
      fieldgroup_in_MET_filedir_names="${field_group}${accum_hh}h"
      ;;

    "REFC"|"RETOP")
      _obtype_="MRMS"
      _grid_or_point_="grid"
      fieldgroup_in_MET_filedir_names="${field_group}"
      ;;

    "SFC"|"UPA")
      _obtype_="NDAS"
      _grid_or_point_="point"
      fieldgroup_in_MET_filedir_names="${field_group}"
      ;;

    *)
      print_err_msg_exit "\
A method for setting verification parameters has not been specified for
this field group (field_group):
  field_group = \"${field_group}\""
      ;;

  esac
#
#-----------------------------------------------------------------------
#
# Set output variables.
#
#-----------------------------------------------------------------------
#
  if [ ! -z "${outvarname_obtype}" ]; then
    printf -v ${outvarname_obtype} "%s" "${_obtype_}"
  fi

  if [ ! -z "${outvarname_grid_or_point}" ]; then
    printf -v ${outvarname_grid_or_point} "%s" "${_grid_or_point_}"
  fi

  if [ ! -z "${outvarname_fieldgroup_in_MET_filedir_names}" ]; then
    printf -v ${outvarname_fieldgroup_in_MET_filedir_names} "%s" "${fieldgroup_in_MET_filedir_names}"
  fi
#
#-----------------------------------------------------------------------
#
# Restore the shell options saved at the beginning of this script/function.
#
#-----------------------------------------------------------------------
#
  { restore_shell_opts; } > /dev/null 2>&1

}
